// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.flp.core.domain;

import io.flp.core.domain.UserRole;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserRole_Roo_Configurable {
    
    declare @type: UserRole: @Configurable;
    
}
